import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useContext } from "react";
import { Logo } from "../components/Logo";
import UserContext from "../utils/context/userContext";

export default function Home() {
  const {user, setUser} = useContext(UserContext);
  const router = useRouter();

  useEffect(() => {
    const storedUser = localStorage.getItem("user");
    if (storedUser !== null) {
      setUser(JSON.parse(storedUser));
      router.replace("/dashboard");
    } else {
      setTimeout(() => {
        const opening = document.getElementById("opening");
        opening.classList.add("hidden");
      }, 2000);
    }

  }, []);

  return (
    <div className="w-full">
      <Head>
        <title>Money Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        id="opening"
        className="bg-blue-main w-full h-screen absolute top-0 left-0 flex flex-col justify-center items-center z-10"
      >
        <Logo />
        <h1 className="text-2xl text-white mt-[20px]">Money Manager</h1>
      </div>
      <main className="bg-blue-main flex flex-col justify-center items-center h-screen px-10 text-white text-center">
        <div data-aos="fade-right" data-aos-delay="2000">
          <Logo />
        </div>
        <h1
          className="text-2xl mt-[20px]"
          data-aos="fade-right"
          data-aos-delay="2100"
        >
          Money Manager
        </h1>
        <div className="w-full flex flex-col gap-3 mt-10">
          <Link href="/signup">
            <div
              className="w-full bg-blue-button rounded py-1 shadow-button cursor-pointer"
              data-aos="fade-right"
              data-aos-delay="2200"
            >
              Sign Up
            </div>
          </Link>
          <Link href="/login">
            <div
              className="w-full bg-blue-button rounded py-1 shadow-button cursor-pointer"
              data-aos="fade-right"
              data-aos-delay="2400"
            >
              Login
            </div>
          </Link>
        </div>
      </main>
    </div>
  );
}
