import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Money Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className='text-2xl'>Money Manager</h1>
      </main>
    </div>
  )
}
