import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Money Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-blue-main flex flex-col justify-center items-center h-screen'>
        <h1 className='text-2xl text-white'>Money Manager</h1>
        <Link href="/login">
          Login
        </Link>
      </main>
    </div>
  )
}
