import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Money Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-blue-main flex flex-col justify-center items-center h-screen px-10 text-white text-center">
        <h1 className="text-2xl ">Money Manager</h1>
        <div className="w-full flex flex-col gap-3 mt-10">
          <Link href="/login">
            <div className="w-full bg-blue-button rounded py-1 shadow-button cursor-pointer">
              Login
            </div>
          </Link>
          <Link href="/login">
            <div className="w-full bg-blue-button rounded py-1 shadow-button cursor-pointer">
              Sign Up
            </div>
          </Link>
        </div>
      </main>
    </div>
  );
}
